[package]
name = "audio_synthesis"
version = "0.1.0"
edition = "2021"
authors = ["Anti"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.17.1"
druid = "0.8.3"